/*
 * MATLAB Compiler: 4.0 (R14)
 * Date: Fri Apr 06 04:43:08 2007
 * Arguments: "-B" "macro_default" "-m" "-W" "main" "-T" "link:exe" "-v"
 * "testcompile.m" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_testcompile_public_data[] = {'3', '0', '8', '1',
                                                       '9', 'D', '3', '0',
                                                       '0', 'D', '0', '6',
                                                       '0', '9', '2', 'A',
                                                       '8', '6', '4', '8',
                                                       '8', '6', 'F', '7',
                                                       '0', 'D', '0', '1',
                                                       '0', '1', '0', '1',
                                                       '0', '5', '0', '0',
                                                       '0', '3', '8', '1',
                                                       '8', 'B', '0', '0',
                                                       '3', '0', '8', '1',
                                                       '8', '7', '0', '2',
                                                       '8', '1', '8', '1',
                                                       '0', '0', 'C', '4',
                                                       '9', 'C', 'A', 'C',
                                                       '3', '4', 'E', 'D',
                                                       '1', '3', 'A', '5',
                                                       '2', '0', '6', '5',
                                                       '8', 'F', '6', 'F',
                                                       '8', 'E', '0', '1',
                                                       '3', '8', 'C', '4',
                                                       '3', '1', '5', 'B',
                                                       '4', '3', '1', '5',
                                                       '2', '7', '7', 'E',
                                                       'D', '3', 'F', '7',
                                                       'D', 'A', 'E', '5',
                                                       '3', '0', '9', '9',
                                                       'D', 'B', '0', '8',
                                                       'E', 'E', '5', '8',
                                                       '9', 'F', '8', '0',
                                                       '4', 'D', '4', 'B',
                                                       '9', '8', '1', '3',
                                                       '2', '6', 'A', '5',
                                                       '2', 'C', 'C', 'E',
                                                       '4', '3', '8', '2',
                                                       'E', '9', 'F', '2',
                                                       'B', '4', 'D', '0',
                                                       '8', '5', 'E', 'B',
                                                       '9', '5', '0', 'C',
                                                       '7', 'A', 'B', '1',
                                                       '2', 'E', 'D', 'E',
                                                       '2', 'D', '4', '1',
                                                       '2', '9', '7', '8',
                                                       '2', '0', 'E', '6',
                                                       '3', '7', '7', 'A',
                                                       '5', 'F', 'E', 'B',
                                                       '5', '6', '8', '9',
                                                       'D', '4', 'E', '6',
                                                       '0', '3', '2', 'F',
                                                       '6', '0', 'C', '4',
                                                       '3', '0', '7', '4',
                                                       'A', '0', '4', 'C',
                                                       '2', '6', 'A', 'B',
                                                       '7', '2', 'F', '5',
                                                       '4', 'B', '5', '1',
                                                       'B', 'B', '4', '6',
                                                       '0', '5', '7', '8',
                                                       '7', '8', '5', 'B',
                                                       '1', '9', '9', '0',
                                                       '1', '4', '3', '1',
                                                       '4', 'A', '6', '5',
                                                       'F', '0', '9', '0',
                                                       'B', '6', '1', 'F',
                                                       'C', '2', '0', '1',
                                                       '6', '9', '4', '5',
                                                       '3', 'B', '5', '8',
                                                       'F', 'C', '8', 'B',
                                                       'A', '4', '3', 'E',
                                                       '6', '7', '7', '6',
                                                       'E', 'B', '7', 'E',
                                                       'C', 'D', '3', '1',
                                                       '7', '8', 'B', '5',
                                                       '6', 'A', 'B', '0',
                                                       'F', 'A', '0', '6',
                                                       'D', 'D', '6', '4',
                                                       '9', '6', '7', 'C',
                                                       'B', '1', '4', '9',
                                                       'E', '5', '0', '2',
                                                       '0', '1', '1', '1'
                                                       , '\0'};

const char *__MCC_testcompile_name_data = "testcompile";

const char *__MCC_testcompile_root_data = "";

const unsigned char __MCC_testcompile_session_data[] = {'8', '6', '9', '4',
                                                        'B', '4', 'F', 'F',
                                                        'E', 'B', 'E', 'B',
                                                        'B', '3', '7', 'D',
                                                        '2', '0', 'B', '7',
                                                        '7', 'B', '1', '1',
                                                        '9', '0', 'C', 'D',
                                                        '1', '7', '5', '2',
                                                        '6', 'B', '3', '2',
                                                        '8', 'C', 'A', 'D',
                                                        '1', 'E', '2', '5',
                                                        '7', '8', '4', '3',
                                                        '1', '0', 'D', '0',
                                                        '4', '1', 'A', 'F',
                                                        '6', '3', 'B', '7',
                                                        '2', '8', 'D', '1',
                                                        '7', '3', 'F', 'F',
                                                        'B', '0', '1', '1',
                                                        'E', 'F', '3', 'D',
                                                        '0', '9', 'C', 'B',
                                                        '2', '4', '7', '4',
                                                        '7', '6', 'D', '1',
                                                        '2', '1', 'A', '6',
                                                        '2', '4', 'F', '7',
                                                        '5', '2', '6', '7',
                                                        '5', '6', '7', '3',
                                                        '0', 'B', '7', 'E',
                                                        '5', '7', '8', '6',
                                                        '3', 'A', 'A', '7',
                                                        '2', 'D', 'B', '3',
                                                        '6', '4', 'A', 'C',
                                                        '6', 'C', '6', '7',
                                                        '8', '4', '6', 'F',
                                                        'E', '2', '1', '2',
                                                        '8', '0', '7', '8',
                                                        'F', '4', '1', '3',
                                                        '6', '0', '1', '5',
                                                        '9', 'D', '7', 'B',
                                                        '5', '8', '0', '7',
                                                        '1', '3', 'A', '5',
                                                        'A', 'C', '6', 'B',
                                                        '1', 'F', '0', '1',
                                                        '8', 'E', '2', 'C',
                                                        '1', 'E', '7', 'A',
                                                        '9', '1', '6', '4',
                                                        'C', '2', '4', '3',
                                                        '9', 'B', '4', '5',
                                                        '1', '6', '4', '6',
                                                        '6', '3', 'D', '8',
                                                        '8', '7', '5', 'B',
                                                        '0', 'C', '0', '1',
                                                        'B', '6', 'A', '0',
                                                        '1', '3', '9', '2',
                                                        '3', 'B', '1', '4',
                                                        '1', '8', 'F', '7',
                                                        '9', '7', '0', '8',
                                                        '4', '9', '0', 'C',
                                                        '6', 'F', '4', '6',
                                                        '9', '3', 'B', '5',
                                                        '8', '4', '0', '6',
                                                        '9', 'C', 'F', '1',
                                                        '0', '0', '4', '4',
                                                        '0', 'A', '9', '0',
                                                        '0', 'A', '8', '7'
                                                        , '\0'};

const char *__MCC_testcompile_matlabpath_data[] = {"testcompile/", "APIT/",
                                                   "toolbox/compiler/deploy/",
                                                   "$TOOLBOXMATLABDIR/general/",
                                                   "$TOOLBOXMATLABDIR/ops/",
                                                   "$TOOLBOXMATLABDIR/lang/",
                                                   "$TOOLBOXMATLABDIR/elmat/",
                                                   "$TOOLBOXMATLABDIR/elfun/",
                                                   "$TOOLBOXMATLABDIR/specfun/",
                                                   "$TOOLBOXMATLABDIR/matfun/",
                                                   "$TOOLBOXMATLABDIR/datafun/",
                                                   "$TOOLBOXMATLABDIR/polyfun/",
                                                   "$TOOLBOXMATLABDIR/funfun/",
                                                   "$TOOLBOXMATLABDIR/sparfun/",
                                                   "$TOOLBOXMATLABDIR/scribe/",
                                                   "$TOOLBOXMATLABDIR/graph2d/",
                                                   "$TOOLBOXMATLABDIR/graph3d/",
                                                   "$TOOLBOXMATLABDIR/specgraph/",
                                                   "$TOOLBOXMATLABDIR/graphics/",
                                                   "$TOOLBOXMATLABDIR/uitools/",
                                                   "$TOOLBOXMATLABDIR/strfun/",
                                                   "$TOOLBOXMATLABDIR/imagesci/",
                                                   "$TOOLBOXMATLABDIR/iofun/",
                                                   "$TOOLBOXMATLABDIR/audiovideo/",
                                                   "$TOOLBOXMATLABDIR/timefun/",
                                                   "$TOOLBOXMATLABDIR/datatypes/",
                                                   "$TOOLBOXMATLABDIR/verctrl/",
                                                   "$TOOLBOXMATLABDIR/codetools/",
                                                   "$TOOLBOXMATLABDIR/helptools/",
                                                   "$TOOLBOXMATLABDIR/winfun/",
                                                   "$TOOLBOXMATLABDIR/demos/",
                                                   "toolbox/local/",
                                                   "toolbox/compiler/"};
const int __MCC_testcompile_matlabpath_data_count = 33;

const char *__MCC_testcompile_mcr_application_options[] = { "" };
const int __MCC_testcompile_mcr_application_option_count = 0;
const char *__MCC_testcompile_mcr_runtime_options[] = { "" };
const int __MCC_testcompile_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


